# NOTE: This Docker image is for development purposes only.

version: "3.8"

services:
  bot:
    build: .
    image: telegram-twitter-bot
    ports:
      - 8000:8000
    depends_on:
      - redis
  pg:
    image: postgres
    ports:
      - "5432:5432"
#    environment:
#      -

# docker-compose -f ./docker-compose.yml up -d --build